sudo: required
dist: xenial
language: cpp

cache:
  - apt
  - directories:

compiler:
  - g++

os:
  - unix

addons:
  ssh_known_hosts:
    - github.com
    - frs.sourceforge.net

env:
  global:
    - SOURCE_DIR=$TRAVIS_BUILD_DIR
    - RABBITIM_USE_REPOSITORIES="TRUE"
    - QMAKE=qmake

  matrix:
    - BUILD_TARGERT="unix" QT_VERSION_DIR=512 QT_VERSION=5.12.3 DOWNLOAD_QT=FALSE GENERATORS="Unix Makefiles"
    - BUILD_TARGERT="unix" QT_VERSION_DIR=511 QT_VERSION=5.11.3 DOWNLOAD_QT=FALSE STATIC=ON GENERATORS="Unix Makefiles"

    - BUILD_TARGERT="unix" BUILD_ARCH="unix" QT_VERSION_DIR=5.12 QT_VERSION=5.12.6 DOWNLOAD_QT=TRUE GENERATORS="Unix Makefiles"

    - BUILD_TARGERT="android" BUILD_ARCH="armeabi-v7a" ANDROID_ARM_NEON=ON QT_VERSION_DIR=5.13 QT_VERSION=5.13.2 ANDROID_API=android-24 DOWNLOAD_QT=TRUE GENERATORS="Unix Makefiles"
    - BUILD_TARGERT="android" BUILD_ARCH="armeabi-v7a" ANDROID_ARM_NEON=ON QT_VERSION_DIR=5.12 QT_VERSION=5.12.6 ANDROID_API=android-24 DOWNLOAD_QT=TRUE GENERATORS="Unix Makefiles"
    - BUILD_TARGERT="android" BUILD_ARCH="x86" QT_VERSION_DIR=5.12 QT_VERSION=5.12.6 ANDROID_API=android-24 DOWNLOAD_QT=TRUE GENERATORS="Unix Makefiles"

before_install:
  - echo "TRAVIS_OS_NAME=${TRAVIS_OS_NAME}"
  - sudo apt-get install -y -qq xvfb xpra
  - sudo Xvfb :99 -ac &
  - export DISPLAY=:99.0
  - mkdir ${SOURCE_DIR}/Tools
  - export VERSION="v0.0.8"
  
install:
  - cd ${SOURCE_DIR}
  - git clone https://github.com/KangLin/RabbitCommon.git
  - export RabbitCommon_DIR="`pwd`/RabbitCommon"
  - bash ci/build-install-tools.sh > /dev/null
#  - |
#    if [ "$BUILD_TARGERT"="unix" -a -z "$RABBIT_ARCH" ]; then
#        source /opt/qt511/bin/qt511-env.sh
#    fi

before_script:
  - cd ${SOURCE_DIR}

script:
  - bash ${SOURCE_DIR}/ci/build.sh ${SOURCE_DIR}

notifications:
  email: kl222@126.com
  on_success: never  # [always|never|change]
  on_failure: always
