#TODO: Change version
version: 'v0.0.3.{build}'

configuration:
  - Release
  - Debug

platform:
  - x86
  - x64

environment:
  matrix:
  - BUILD_TARGERT: android
    CMAKE_PARAS: -DANDROID_NATIVE_API_LEVEL=android-18 -DANDROID_ABI="armeabi-v7a with NEON"
    RABBIT_TOOLCHAIN_VERSION: 530
    QT_VERSION: 5.9.5
    QT_VERSION_DIR: 5.9

  - BUILD_TARGERT: windows_msvc
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    RABBIT_TOOLCHAIN_VERSION: 15
    CMAKE_PARAS: -DBUILD_GPXMODEL=OFF

  - BUILD_TARGERT: windows_msvc
    RABBIT_TOOLCHAIN_VERSION: 14
    QT_ROOT: C:\Qt\5.10\msvc2015
    
  - BUILD_TARGERT: windows_msvc
    RABBIT_TOOLCHAIN_VERSION: 12
    CMAKE_PARAS: -DBUILD_SHARED_LIBS=OFF -DBUILD_APP=OFF
  
  - BUILD_TARGERT: windows_msvc
    RABBIT_TOOLCHAIN_VERSION: 12
    CMAKE_PARAS: -DBUILD_SHARED_LIBS=OFF -DBUILD_GPXMODEL=OFF 
    QT_ROOT: C:\Qt\5.6\msvc2013

  - BUILD_TARGERT: windows_mingw
    RABBIT_TOOLCHAIN_VERSION: 530

init:
  - set RABBIT_CONFIG=%configuration%
  - set RABBIT_ARCH=%platform%

install:
  - if "%BUILD_TARGERT%"=="windows_msvc" (if %RABBIT_TOOLCHAIN_VERSION% LSS 15 (call "C:\Program Files (x86)\Microsoft Visual Studio %RABBIT_TOOLCHAIN_VERSION%.0\VC\vcvarsall.bat" %PLATFORM%) else (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%))
  - set RABBIT_BUILD_PREFIX="%APPVEYOR_BUILD_FOLDER%\install"

before_build:
  - if "%BUILD_TARGERT%"=="android" C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%/ci/build-install-tools-windows.sh

build_script:
  - del C:\msys64\usr\bin\link.exe
  - C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%\ci\build_script\build.sh
  - cd %APPVEYOR_BUILD_FOLDER%  

artifacts:
  - path: install
    name: TransformCoordinate_$(BUILD_TARGERT)$(RABBIT_TOOLCHAIN_VERSION)_$(CONFIGURATION)_$(appveyor_build_version)
    type: zip

test: off

deploy:
  - provider: GitHub
    #release: TransformCoordinate-$(appveyor_build_version)
    description: 'Release TransformCoordinate $(APPVEYOR_REPO_TAG_NAME) on windows'
    #token : https://github.com/settings/tokens password encrypt: https://ci.appveyor.com/tools/encrypt
    auth_token:
      secure: xgIFN2iAfgj1gsWabdHrmFXvj0rce/ZWtKUwm3aDUNfLGu+kO/q94MYD8a46AbDL
    on:
      appveyor_repo_tag: true        # deploy on tag push only
      BUILD_TARGERT: windows_msvc
      RABBIT_TOOLCHAIN_VERSION: 14
      configuration: Release
      platform: x86
