#TODO: Change version
version: 'v0.0.1.{build}'

configuration:
  - Release
  - Debug

environment:
  matrix:

init:

  
install:

before_build:

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cmake ..
  - cmake --build . --target install --config %CONFIGURATION%

#after_build:

artifacts:
  #- path: build_$(BUILD_TARGERT)/install
  #  name: RabbitGIS_$(BUILD_TARGERT)$(TOOLCHAIN_VERSION)_$(AUTOBUILD_ARCH)_$(QT_VERSION)_v$(appveyor_build_version)
  #  type: zip

  - path: build_${BUILD_TARGERT}/RabbitGIS-Setup-*.exe
    name: RabbitGIS_$(BUILD_TARGERT)$(TOOLCHAIN_VERSION)_$(AUTOBUILD_ARCH)_$(QT_VERSION)_v$(appveyor_build_version)
#    type: zip

test: off

deploy:
  - provider: FTP #https://sourceforge.net/p/forge/documentation/Release%20Files%20for%20Download/#scp
    protocol: sftp #https://sourceforge.net/p/forge/documentation/SFTP/
    host: frs.sourceforge.net
    username: kl222,rabbitgis
    #password encrypt: https://ci.appveyor.com/tools/encrypt
    password:
      secure: 2WEtOQrdty3V3g0aEVvS3Q==
    folder: pfs   #link pfs to /home/frs/project/r/ra/rabbitgis
    draft: false
    active_mode: false
    on:
      #branch: master
      appveyor_repo_tag: true
      BUILD_TARGERT: windows_msvc
      TOOLCHAIN_VERSION: 14
      QT_VERSION: qt5.7.1


  - provider: GitHub
    #release: RabbitGIS-v$(appveyor_build_version)
    description: 'Release RabbitGIS $(APPVEYOR_REPO_TAG_NAME) on windows'
    #token : https://github.com/settings/tokens password encrypt: https://ci.appveyor.com/tools/encrypt
    auth_token:
      secure: xgIFN2iAfgj1gsWabdHrmFXvj0rce/ZWtKUwm3aDUNfLGu+kO/q94MYD8a46AbDL
    #artifact: RabbitGIS_$(BUILD_TARGERT)$(TOOLCHAIN_VERSION)_$(AUTOBUILD_ARCH)_$(QT_VERSION)_v$(appveyor_build_version)
    #draft: true
    #prerelease: true
    on:
      BUILD_TARGERT: windows_msvc
      TOOLCHAIN_VERSION: 14
      QT_VERSION: qt5.7.1
      AUTOBUILD_ARCH: x86
      appveyor_repo_tag: true        # deploy on tag push only
