#TODO: Change version
version: 'v0.0.3.{build}'

configuration:
  - Release
  - Debug

platform:
  - x86
  - x64

environment:
  matrix:
  - BUILD_TARGERT: windows_msvc
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    RABBIT_TOOLCHAIN_VERSION: 15
    CMAKE_PARAS: -DBUILD_GPXMODEL=OFF

  - BUILD_TARGERT: windows_msvc
    RABBIT_TOOLCHAIN_VERSION: 14
    QT_ROOT: C:\Qt\5.10\msvc2015
    
  - BUILD_TARGERT: windows_msvc
    RABBIT_TOOLCHAIN_VERSION: 12
    CMAKE_PARAS: -DBUILD_SHARED_LIBS=OFF -DBUILD_APP=OFF
  
  - BUILD_TARGERT: windows_msvc
    RABBIT_TOOLCHAIN_VERSION: 12
    CMAKE_PARAS: -DBUILD_SHARED_LIBS=OFF -DBUILD_GPXMODEL=OFF 
    QT_ROOT: C:\Qt\5.6\msvc2013

  - BUILD_TARGERT: windows_mingw
    RABBIT_TOOLCHAIN_VERSION: 530
    
  - BUILD_TARGERT: android
    CMAKE_PARAS: -DANDROID_NATIVE_API_LEVEL=android-18 -DANDROID_ABI="armeabi-v7a with NEON"
    QT_VERSION: 5.9.5
    QT_VERSION_DIR: 5.9

init:
  - if NOT "%GENERATORS%"=="MSYS Makefiles" if "%PLATFORM%"=="x64" if NOT "%QT_ROOT%"=="" set QT_ROOT=%QT_ROOT%_64
  - set RABBIT_CONFIG=%configuration%
  - set RABBIT_ARCH=%platform%
  
install:
  - if "%BUILD_TARGERT%"=="windows_msvc" if %RABBIT_TOOLCHAIN_VERSION% LSS 15 (call "C:\Program Files (x86)\Microsoft Visual Studio %RABBIT_TOOLCHAIN_VERSION%.0\VC\vcvarsall.bat" %PLATFORM%) else (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%)
  - set RABBIT_BUILD_PREFIX="%APPVEYOR_BUILD_FOLDER%\install"
  
before_build:
  - if "%QT_ROOT%"=="" SET CMAKE_PARAS=-DBUILD_APP=OFF %CMAKE_PARAS%
  - if NOT "%QT_ROOT%"=="" SET CMAKE_PARAS=-DQt5_DIR=%QT_ROOT%\lib\cmake\Qt5 %CMAKE_PARAS%
  - cd %APPVEYOR_BUILD_FOLDER%\ci\build_script
  - del C:\msys64\usr\bin\link.exe
  - C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%\ci\build_script\build.sh %BUILD_TARGERT%
  - cd %APPVEYOR_BUILD_FOLDER%  
  - if "%BUILD_TARGERT%"=="android" C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%/ci/build-install-tools-windows.sh
  - if "%BUILD_TARGERT%"=="android" set ANDROID_SDK=%APPVEYOR_BUILD_FOLDER%/tools/android-sdk
  - if "%BUILD_TARGERT%"=="android" set ANDROID_NDK=%APPVEYOR_BUILD_FOLDER%/tools/android-ndk
  - if "%BUILD_TARGERT%"=="android" SET CMAKE_PARAS=-DQt5_DIR=C:/projects/TransformCoordinate/Tools/Qt/Qt%QT_VERSION%/%QT_VERSION%/android_armv7/lib/cmake/Qt5 %CMAKE_PARAS%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - echo "cmake .. -G%GENERATORS% -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\install %CMAKE_PARAS% "
  - if "%BUILD_TARGERT%"=="android"  cmake .. -G"MSYS Makefiles" -DCMAKE_INSTALL_PREFIX="%RABBIT_BUILD_PREFIX%" -DCMAKE_MAKE_PROGRAM=C:\msys64\usr\bin\make.exe -DCMAKE_TOOLCHAIN_FILE="%APPVEYOR_BUILD_FOLDER%/android.toolchain.cmake" %CMAKE_PARAS%
  - if NOT "%BUILD_TARGERT%"=="android" cmake .. -G"%GENERATORS%" -DCMAKE_INSTALL_PREFIX="%RABBIT_BUILD_PREFIX%" %CMAKE_PARAS%
  - cmake --build . --target install --config %CONFIGURATION%
  - if "%GENERATORS%"=="MSYS Makefiles" set GENERATORS=%GENERATORS%_%PLATFORM%

#after_build:

artifacts:
  - path: install
    name: TransformCoordinate_${BUILD_TARGERT}_$(GENERATORS)_$(CONFIGURATION)_v$(appveyor_build_version)
    type: zip

test: off

deploy:
  - provider: GitHub
    #release: TransformCoordinate-v$(appveyor_build_version)
    description: 'Release TransformCoordinate $(APPVEYOR_REPO_TAG_NAME) on windows'
    #token : https://github.com/settings/tokens password encrypt: https://ci.appveyor.com/tools/encrypt
    auth_token:
      secure: xgIFN2iAfgj1gsWabdHrmFXvj0rce/ZWtKUwm3aDUNfLGu+kO/q94MYD8a46AbDL
    #artifact: TransformCoordinate_$(GENERATORS)_$(CONFIGURATION)_$(appveyor_build_version)
    #draft: true
    #prerelease: true
    on:
      appveyor_repo_tag: true        # deploy on tag push only
      GENERATORS: "Visual Studio 14 2015"
      configuration: Release
