#TODO: Change version
version: '0.0.1.{build}'

configuration:
  - Release
  - Debug

platform:
  - x86
  - x64

environment:
  matrix:
  - GENERATORS: "Visual Studio 15 2017"
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - GENERATORS: "Visual Studio 14 2015" 
    QT_ROOT: C:\Qt\5.10\msvc2015
  - GENERATORS: "Visual Studio 12 2013"
  - GENERATORS: "Visual Studio 11 2012"
  - GENERATORS: "Visual Studio 10 2010"
  #- GENERATORS: "Visual Studio 9 2008"
  - GENERATORS: "MSYS Makefiles"

init:
  - if "%GENERATORS%"=="MSYS Makefiles" if "%PLATFORM%"=="x86" SET PATH=C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin;%PATH%;C:\MinGW\msys\1.0\bin
  - if "%GENERATORS%"=="MSYS Makefiles" if "%PLATFORM%"=="x64" SET PATH=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH%;C:\MinGW\msys\1.0\bin

  #- if NOT "%GENERATORS%"=="MSYS Makefiles" if %RABBIT_TOOLCHAIN_VERSION% LSS 15 (call "C:\Program Files (x86)\Microsoft Visual Studio %RABBIT_TOOLCHAIN_VERSION%.0\VC\vcvarsall.bat" %PLATFORM%) else (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%)
  - if NOT "%GENERATORS%"=="MSYS Makefiles" if "%PLATFORM%"=="x64" set GENERATORS=%GENERATORS% Win64
  - if NOT "%GENERATORS%"=="MSYS Makefiles" if "%PLATFORM%"=="x64" if NOT "%QT_ROOT%"=="" set QT_ROOT=%QT_ROOT%_64

install:

before_build:
  - if "%QT_ROOT%"=="" SET CMAKE_PARAS=-DBUILD_APP=OFF
  - if NOT "%QT_ROOT%"=="" SET CMAKE_PARAS=-DQt5_DIR=%QT_ROOT%\lib\cmake\Qt5
  
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - echo "cmake .. -G%GENERATORS% -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\install %CMAKE_PARAS% "
  - cmake .. -G"%GENERATORS%" -DCMAKE_INSTATLL_PREFIX="%APPVEYOR_BUILD_FOLDER%\install" %CMAKE_PARAS%
  - cmake --build . --target install --config %CONFIGURATION%
  - if "%GENERATORS%"=="MSYS Makefiles" set GENERATORS=%GENERATORS%_%PLATFORM%

#after_build:

artifacts:
  - path: install
    name: TransformCoordinate_$(GENERATORS)_$(CONFIGURATION)_v$(appveyor_build_version)
    type: zip

test: off

deploy:
  - provider: GitHub
    #release: TransformCoordinate-v$(appveyor_build_version)
    description: 'Release TransformCoordinate $(APPVEYOR_REPO_TAG_NAME) on windows'
    #token : https://github.com/settings/tokens password encrypt: https://ci.appveyor.com/tools/encrypt
    auth_token:
      secure: xgIFN2iAfgj1gsWabdHrmFXvj0rce/ZWtKUwm3aDUNfLGu+kO/q94MYD8a46AbDL
    #artifact: TransformCoordinate_$(GENERATORS)_$(CONFIGURATION)_$(appveyor_build_version)
    #draft: true
    #prerelease: true
    on:
      appveyor_repo_tag: true        # deploy on tag push only
