name: build_ubuntu

on:
  workflow_call:
    outputs:
      name:
        description: "The artifact name"
        value: ${{ jobs.build_ubuntu.outputs.name }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build_ubuntu:
    strategy:
      matrix:
        BUILD_TYPE: [Release, Debug]

    runs-on: ubuntu-latest

    env:
      BUILD_TYPE:  ${{ matrix.BUILD_TYPE }}
      SOURCE_DIR:  ${{github.workspace}}/.cache/source
      TOOSL_DIR:   ${{github.workspace}}/.cache/tools
      INSTALL_DIR: ${{github.workspace}}/.cache/install_ubuntu
      TransformCoordinate_VERSION: 1.0.13
      artifact_name: build_ubuntu

    # Map the job outputs to step outputs
    outputs:
      name: ${{ env.artifact_name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Make directories
        run: |
          cmake -E make_directory ${{env.SOURCE_DIR}}
          cmake -E make_directory ${{env.TOOSL_DIR}}
          cmake -E make_directory ${{env.INSTALL_DIR}}
          cmake -E make_directory ${{github.workspace}}/build

      - name: Install apt packages
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install -y -q cmake build-essential xvfb xpra \
              libglu1-mesa-dev libpulse-mainloop-glib0 \
              debhelper fakeroot \
              qttools5-dev qttools5-dev-tools qtbase5-dev qtbase5-dev-tools \
              qtmultimedia5-dev qtlocation5-dev libqt5svg5-dev \
              qtpositioning5-dev qtwebengine5-dev \
              libcmark-gfm-dev libcmark-gfm-extensions-dev

      - name: Build TransformCoordinate
        working-directory: ${{github.workspace}}/build
        run: |
          cmake ${{github.workspace}} \
                -DCMARK_SHARED=OFF \
                -DCMARK_TESTS=OFF \
                -DCMARK_STATIC=ON \
                -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} \
                -DCMAKE_INSTALL_PREFIX=`pwd`/install \
                -DCMAKE_PREFIX_PATH=${{ env.INSTALL_DIR }}/lib/cmake \
                -DINSTALL_QT=OFF \
                -DBUILD_APP=OFF
          cmake --build . --config ${{ matrix.BUILD_TYPE }} --target install
          cmake --build . --config ${{ matrix.BUILD_TYPE }} --target package
          7z a TransformCoordinate_${{env.TransformCoordinate_VERSION}}_ubuntu_${{matrix.BUILD_TYPE}}.zip ./install/*

      - name: Update artifact
        #if: ${{ matrix.BUILD_TYPE == 'Release' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}
          path: |
            ${{github.workspace}}/build/TransformCoordinate-*.tar.gz
            ${{github.workspace}}/build/TransformCoordinate_${{env.TransformCoordinate_VERSION}}_ubuntu_${{matrix.BUILD_TYPE}}.zip

#    - name: Upload To Github Release
#      if: ${{ matrix.BUILD_TYPE == 'Release' && startsWith(github.ref, 'refs/tags/') }}
#      uses: softprops/action-gh-release@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        prerelease: true
#        body: |
#           [:cn: 修改日志](ChangeLog_zh_CN.md) [:us: Change log](ChangeLog.md)
#        files: |
#            ${{github.workspace}}/TransformCoordinate_${{env.TransformCoordinate_VERSION}}_amd64.deb
